[build]
builder = "DOCKERFILE"
dockerfilePath = "./backend/Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"

[[services]]
name = "code-trainer-backend"

[services.run]
command = "./main"

[services.env]
PORT = "8080"

[services.ports]
port = 8080
protocol = "HTTP"