services:
  - type: web
    name: trenager
    env: docker
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: PORT
        value: "10000"
    healthCheckPath: /health
    plans:
      - name: free
        cpu: 0.25
        memory: 512MB
        maxConcurrentBuilds: 1