FROM golang:1.24-alpine

WORKDIR /app

# Установка компиляторов и интерпретаторов
RUN apk add --no-cache \
    python3 \
    nodejs \
    npm \
    openjdk11 \
    g++ \
    make \
    git

# Копируем исходный код
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Собираем приложение
RUN go build -o main ./cmd/server

EXPOSE 8080

CMD ["./main"]