// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: ai/ai.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserCode      string                 `protobuf:"bytes,2,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	HintLevel     int32                  `protobuf:"varint,4,opt,name=hint_level,json=hintLevel,proto3" json:"hint_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHintRequest) Reset() {
	*x = GetHintRequest{}
	mi := &file_ai_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHintRequest) ProtoMessage() {}

func (x *GetHintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHintRequest.ProtoReflect.Descriptor instead.
func (*GetHintRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{0}
}

func (x *GetHintRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetHintRequest) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *GetHintRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GetHintRequest) GetHintLevel() int32 {
	if x != nil {
		return x.HintLevel
	}
	return 0
}

type GetHintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hint          string                 `protobuf:"bytes,1,opt,name=hint,proto3" json:"hint,omitempty"`
	HintLevel     int32                  `protobuf:"varint,2,opt,name=hint_level,json=hintLevel,proto3" json:"hint_level,omitempty"`
	ExampleCode   string                 `protobuf:"bytes,3,opt,name=example_code,json=exampleCode,proto3" json:"example_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHintResponse) Reset() {
	*x = GetHintResponse{}
	mi := &file_ai_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHintResponse) ProtoMessage() {}

func (x *GetHintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHintResponse.ProtoReflect.Descriptor instead.
func (*GetHintResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{1}
}

func (x *GetHintResponse) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *GetHintResponse) GetHintLevel() int32 {
	if x != nil {
		return x.HintLevel
	}
	return 0
}

func (x *GetHintResponse) GetExampleCode() string {
	if x != nil {
		return x.ExampleCode
	}
	return ""
}

type ReviewCodeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Language        string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	TaskDescription string                 `protobuf:"bytes,3,opt,name=task_description,json=taskDescription,proto3" json:"task_description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReviewCodeRequest) Reset() {
	*x = ReviewCodeRequest{}
	mi := &file_ai_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewCodeRequest) ProtoMessage() {}

func (x *ReviewCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewCodeRequest.ProtoReflect.Descriptor instead.
func (*ReviewCodeRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{2}
}

func (x *ReviewCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ReviewCodeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ReviewCodeRequest) GetTaskDescription() string {
	if x != nil {
		return x.TaskDescription
	}
	return ""
}

type ReviewCodeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	QualityScore    int32                  `protobuf:"varint,1,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	Issues          []string               `protobuf:"bytes,2,rep,name=issues,proto3" json:"issues,omitempty"`
	Suggestions     []string               `protobuf:"bytes,3,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	OverallFeedback string                 `protobuf:"bytes,4,opt,name=overall_feedback,json=overallFeedback,proto3" json:"overall_feedback,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReviewCodeResponse) Reset() {
	*x = ReviewCodeResponse{}
	mi := &file_ai_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewCodeResponse) ProtoMessage() {}

func (x *ReviewCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewCodeResponse.ProtoReflect.Descriptor instead.
func (*ReviewCodeResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{3}
}

func (x *ReviewCodeResponse) GetQualityScore() int32 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *ReviewCodeResponse) GetIssues() []string {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *ReviewCodeResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *ReviewCodeResponse) GetOverallFeedback() string {
	if x != nil {
		return x.OverallFeedback
	}
	return ""
}

type GetRecommendationsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompletedTasks []string               `protobuf:"bytes,2,rep,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	WeakTopics     []string               `protobuf:"bytes,3,rep,name=weak_topics,json=weakTopics,proto3" json:"weak_topics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRecommendationsRequest) Reset() {
	*x = GetRecommendationsRequest{}
	mi := &file_ai_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsRequest) ProtoMessage() {}

func (x *GetRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{4}
}

func (x *GetRecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRecommendationsRequest) GetCompletedTasks() []string {
	if x != nil {
		return x.CompletedTasks
	}
	return nil
}

func (x *GetRecommendationsRequest) GetWeakTopics() []string {
	if x != nil {
		return x.WeakTopics
	}
	return nil
}

type GetRecommendationsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*TaskRecommendation  `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRecommendationsResponse) Reset() {
	*x = GetRecommendationsResponse{}
	mi := &file_ai_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsResponse) ProtoMessage() {}

func (x *GetRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{5}
}

func (x *GetRecommendationsResponse) GetRecommendations() []*TaskRecommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

type TaskRecommendation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	DifficultyScore float32                `protobuf:"fixed32,4,opt,name=difficulty_score,json=difficultyScore,proto3" json:"difficulty_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskRecommendation) Reset() {
	*x = TaskRecommendation{}
	mi := &file_ai_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRecommendation) ProtoMessage() {}

func (x *TaskRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRecommendation.ProtoReflect.Descriptor instead.
func (*TaskRecommendation) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{6}
}

func (x *TaskRecommendation) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRecommendation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskRecommendation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TaskRecommendation) GetDifficultyScore() float32 {
	if x != nil {
		return x.DifficultyScore
	}
	return 0
}

type AskQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	CodeContext   string                 `protobuf:"bytes,2,opt,name=code_context,json=codeContext,proto3" json:"code_context,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskQuestionRequest) Reset() {
	*x = AskQuestionRequest{}
	mi := &file_ai_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskQuestionRequest) ProtoMessage() {}

func (x *AskQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskQuestionRequest.ProtoReflect.Descriptor instead.
func (*AskQuestionRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{7}
}

func (x *AskQuestionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *AskQuestionRequest) GetCodeContext() string {
	if x != nil {
		return x.CodeContext
	}
	return ""
}

func (x *AskQuestionRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type AskQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	CodeExamples  []string               `protobuf:"bytes,2,rep,name=code_examples,json=codeExamples,proto3" json:"code_examples,omitempty"`
	HasCode       bool                   `protobuf:"varint,3,opt,name=has_code,json=hasCode,proto3" json:"has_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskQuestionResponse) Reset() {
	*x = AskQuestionResponse{}
	mi := &file_ai_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskQuestionResponse) ProtoMessage() {}

func (x *AskQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskQuestionResponse.ProtoReflect.Descriptor instead.
func (*AskQuestionResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{8}
}

func (x *AskQuestionResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AskQuestionResponse) GetCodeExamples() []string {
	if x != nil {
		return x.CodeExamples
	}
	return nil
}

func (x *AskQuestionResponse) GetHasCode() bool {
	if x != nil {
		return x.HasCode
	}
	return false
}

var File_ai_ai_proto protoreflect.FileDescriptor

const file_ai_ai_proto_rawDesc = "" +
	"\n" +
	"\vai/ai.proto\x12\x02ai\"\x81\x01\n" +
	"\x0eGetHintRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tuser_code\x18\x02 \x01(\tR\buserCode\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"hint_level\x18\x04 \x01(\x05R\thintLevel\"g\n" +
	"\x0fGetHintResponse\x12\x12\n" +
	"\x04hint\x18\x01 \x01(\tR\x04hint\x12\x1d\n" +
	"\n" +
	"hint_level\x18\x02 \x01(\x05R\thintLevel\x12!\n" +
	"\fexample_code\x18\x03 \x01(\tR\vexampleCode\"n\n" +
	"\x11ReviewCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12)\n" +
	"\x10task_description\x18\x03 \x01(\tR\x0ftaskDescription\"\x9e\x01\n" +
	"\x12ReviewCodeResponse\x12#\n" +
	"\rquality_score\x18\x01 \x01(\x05R\fqualityScore\x12\x16\n" +
	"\x06issues\x18\x02 \x03(\tR\x06issues\x12 \n" +
	"\vsuggestions\x18\x03 \x03(\tR\vsuggestions\x12)\n" +
	"\x10overall_feedback\x18\x04 \x01(\tR\x0foverallFeedback\"~\n" +
	"\x19GetRecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fcompleted_tasks\x18\x02 \x03(\tR\x0ecompletedTasks\x12\x1f\n" +
	"\vweak_topics\x18\x03 \x03(\tR\n" +
	"weakTopics\"^\n" +
	"\x1aGetRecommendationsResponse\x12@\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x16.ai.TaskRecommendationR\x0frecommendations\"\x86\x01\n" +
	"\x12TaskRecommendation\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12)\n" +
	"\x10difficulty_score\x18\x04 \x01(\x02R\x0fdifficultyScore\"o\n" +
	"\x12AskQuestionRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12!\n" +
	"\fcode_context\x18\x02 \x01(\tR\vcodeContext\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"m\n" +
	"\x13AskQuestionResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12#\n" +
	"\rcode_examples\x18\x02 \x03(\tR\fcodeExamples\x12\x19\n" +
	"\bhas_code\x18\x03 \x01(\bR\ahasCode2\x91\x02\n" +
	"\tAIService\x122\n" +
	"\aGetHint\x12\x12.ai.GetHintRequest\x1a\x13.ai.GetHintResponse\x12;\n" +
	"\n" +
	"ReviewCode\x12\x15.ai.ReviewCodeRequest\x1a\x16.ai.ReviewCodeResponse\x12S\n" +
	"\x12GetRecommendations\x12\x1d.ai.GetRecommendationsRequest\x1a\x1e.ai.GetRecommendationsResponse\x12>\n" +
	"\vAskQuestion\x12\x16.ai.AskQuestionRequest\x1a\x17.ai.AskQuestionResponseB)Z'github.com/AllaxSydia/trenager/proto/aib\x06proto3"

var (
	file_ai_ai_proto_rawDescOnce sync.Once
	file_ai_ai_proto_rawDescData []byte
)

func file_ai_ai_proto_rawDescGZIP() []byte {
	file_ai_ai_proto_rawDescOnce.Do(func() {
		file_ai_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_ai_proto_rawDesc), len(file_ai_ai_proto_rawDesc)))
	})
	return file_ai_ai_proto_rawDescData
}

var file_ai_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ai_ai_proto_goTypes = []any{
	(*GetHintRequest)(nil),             // 0: ai.GetHintRequest
	(*GetHintResponse)(nil),            // 1: ai.GetHintResponse
	(*ReviewCodeRequest)(nil),          // 2: ai.ReviewCodeRequest
	(*ReviewCodeResponse)(nil),         // 3: ai.ReviewCodeResponse
	(*GetRecommendationsRequest)(nil),  // 4: ai.GetRecommendationsRequest
	(*GetRecommendationsResponse)(nil), // 5: ai.GetRecommendationsResponse
	(*TaskRecommendation)(nil),         // 6: ai.TaskRecommendation
	(*AskQuestionRequest)(nil),         // 7: ai.AskQuestionRequest
	(*AskQuestionResponse)(nil),        // 8: ai.AskQuestionResponse
}
var file_ai_ai_proto_depIdxs = []int32{
	6, // 0: ai.GetRecommendationsResponse.recommendations:type_name -> ai.TaskRecommendation
	0, // 1: ai.AIService.GetHint:input_type -> ai.GetHintRequest
	2, // 2: ai.AIService.ReviewCode:input_type -> ai.ReviewCodeRequest
	4, // 3: ai.AIService.GetRecommendations:input_type -> ai.GetRecommendationsRequest
	7, // 4: ai.AIService.AskQuestion:input_type -> ai.AskQuestionRequest
	1, // 5: ai.AIService.GetHint:output_type -> ai.GetHintResponse
	3, // 6: ai.AIService.ReviewCode:output_type -> ai.ReviewCodeResponse
	5, // 7: ai.AIService.GetRecommendations:output_type -> ai.GetRecommendationsResponse
	8, // 8: ai.AIService.AskQuestion:output_type -> ai.AskQuestionResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ai_ai_proto_init() }
func file_ai_ai_proto_init() {
	if File_ai_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_ai_proto_rawDesc), len(file_ai_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_ai_proto_goTypes,
		DependencyIndexes: file_ai_ai_proto_depIdxs,
		MessageInfos:      file_ai_ai_proto_msgTypes,
	}.Build()
	File_ai_ai_proto = out.File
	file_ai_ai_proto_goTypes = nil
	file_ai_ai_proto_depIdxs = nil
}
