// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: execution/execution.proto

package execution

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Input         string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	TimeLimitMs   int32                  `protobuf:"varint,4,opt,name=time_limit_ms,json=timeLimitMs,proto3" json:"time_limit_ms,omitempty"`
	MemoryLimitMb int32                  `protobuf:"varint,5,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCodeRequest) Reset() {
	*x = ExecuteCodeRequest{}
	mi := &file_execution_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCodeRequest) ProtoMessage() {}

func (x *ExecuteCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCodeRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCodeRequest) Descriptor() ([]byte, []int) {
	return file_execution_execution_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteCodeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ExecuteCodeRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *ExecuteCodeRequest) GetTimeLimitMs() int32 {
	if x != nil {
		return x.TimeLimitMs
	}
	return 0
}

func (x *ExecuteCodeRequest) GetMemoryLimitMb() int32 {
	if x != nil {
		return x.MemoryLimitMb
	}
	return 0
}

type ExecuteCodeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output          string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error           string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ExecutionTimeMs int64                  `protobuf:"varint,4,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	MemoryUsedBytes int64                  `protobuf:"varint,5,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // completed, timeout, memory_error, runtime_error
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteCodeResponse) Reset() {
	*x = ExecuteCodeResponse{}
	mi := &file_execution_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCodeResponse) ProtoMessage() {}

func (x *ExecuteCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCodeResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCodeResponse) Descriptor() ([]byte, []int) {
	return file_execution_execution_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteCodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteCodeResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecuteCodeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteCodeResponse) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *ExecuteCodeResponse) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *ExecuteCodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ExecuteTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Tests         []*TestCase            `protobuf:"bytes,3,rep,name=tests,proto3" json:"tests,omitempty"`
	TimeLimitMs   int32                  `protobuf:"varint,4,opt,name=time_limit_ms,json=timeLimitMs,proto3" json:"time_limit_ms,omitempty"`
	MemoryLimitMb int32                  `protobuf:"varint,5,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTestRequest) Reset() {
	*x = ExecuteTestRequest{}
	mi := &file_execution_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTestRequest) ProtoMessage() {}

func (x *ExecuteTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTestRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTestRequest) Descriptor() ([]byte, []int) {
	return file_execution_execution_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteTestRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteTestRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ExecuteTestRequest) GetTests() []*TestCase {
	if x != nil {
		return x.Tests
	}
	return nil
}

func (x *ExecuteTestRequest) GetTimeLimitMs() int32 {
	if x != nil {
		return x.TimeLimitMs
	}
	return 0
}

func (x *ExecuteTestRequest) GetMemoryLimitMb() int32 {
	if x != nil {
		return x.MemoryLimitMb
	}
	return 0
}

type TestCase struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Input          string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	ExpectedOutput string                 `protobuf:"bytes,2,opt,name=expected_output,json=expectedOutput,proto3" json:"expected_output,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestCase) Reset() {
	*x = TestCase{}
	mi := &file_execution_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCase) ProtoMessage() {}

func (x *TestCase) ProtoReflect() protoreflect.Message {
	mi := &file_execution_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCase.ProtoReflect.Descriptor instead.
func (*TestCase) Descriptor() ([]byte, []int) {
	return file_execution_execution_proto_rawDescGZIP(), []int{3}
}

func (x *TestCase) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TestCase) GetExpectedOutput() string {
	if x != nil {
		return x.ExpectedOutput
	}
	return ""
}

type TestResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TestId          string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Passed          bool                   `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	ActualOutput    string                 `protobuf:"bytes,3,opt,name=actual_output,json=actualOutput,proto3" json:"actual_output,omitempty"`
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ExecutionTimeMs int64                  `protobuf:"varint,5,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TestResult) Reset() {
	*x = TestResult{}
	mi := &file_execution_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResult) ProtoMessage() {}

func (x *TestResult) ProtoReflect() protoreflect.Message {
	mi := &file_execution_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResult.ProtoReflect.Descriptor instead.
func (*TestResult) Descriptor() ([]byte, []int) {
	return file_execution_execution_proto_rawDescGZIP(), []int{4}
}

func (x *TestResult) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *TestResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *TestResult) GetActualOutput() string {
	if x != nil {
		return x.ActualOutput
	}
	return ""
}

func (x *TestResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TestResult) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

type ExecuteTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllPassed     bool                   `protobuf:"varint,1,opt,name=all_passed,json=allPassed,proto3" json:"all_passed,omitempty"`
	Results       []*TestResult          `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	PassedCount   int32                  `protobuf:"varint,3,opt,name=passed_count,json=passedCount,proto3" json:"passed_count,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTestResponse) Reset() {
	*x = ExecuteTestResponse{}
	mi := &file_execution_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTestResponse) ProtoMessage() {}

func (x *ExecuteTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTestResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTestResponse) Descriptor() ([]byte, []int) {
	return file_execution_execution_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteTestResponse) GetAllPassed() bool {
	if x != nil {
		return x.AllPassed
	}
	return false
}

func (x *ExecuteTestResponse) GetResults() []*TestResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ExecuteTestResponse) GetPassedCount() int32 {
	if x != nil {
		return x.PassedCount
	}
	return 0
}

func (x *ExecuteTestResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetExecutionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionStatusRequest) Reset() {
	*x = GetExecutionStatusRequest{}
	mi := &file_execution_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionStatusRequest) ProtoMessage() {}

func (x *GetExecutionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionStatusRequest) Descriptor() ([]byte, []int) {
	return file_execution_execution_proto_rawDescGZIP(), []int{6}
}

func (x *GetExecutionStatusRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type ExecutionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // pending, running, completed, failed
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionStatus) Reset() {
	*x = ExecutionStatus{}
	mi := &file_execution_execution_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionStatus) ProtoMessage() {}

func (x *ExecutionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_execution_execution_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionStatus.ProtoReflect.Descriptor instead.
func (*ExecutionStatus) Descriptor() ([]byte, []int) {
	return file_execution_execution_proto_rawDescGZIP(), []int{7}
}

func (x *ExecutionStatus) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionStatus) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExecutionStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_execution_execution_proto protoreflect.FileDescriptor

const file_execution_execution_proto_rawDesc = "" +
	"\n" +
	"\x19execution/execution.proto\x12\texecution\"\xa6\x01\n" +
	"\x12ExecuteCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\x12\"\n" +
	"\rtime_limit_ms\x18\x04 \x01(\x05R\vtimeLimitMs\x12&\n" +
	"\x0fmemory_limit_mb\x18\x05 \x01(\x05R\rmemoryLimitMb\"\xcd\x01\n" +
	"\x13ExecuteCodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12*\n" +
	"\x11execution_time_ms\x18\x04 \x01(\x03R\x0fexecutionTimeMs\x12*\n" +
	"\x11memory_used_bytes\x18\x05 \x01(\x03R\x0fmemoryUsedBytes\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\xbb\x01\n" +
	"\x12ExecuteTestRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12)\n" +
	"\x05tests\x18\x03 \x03(\v2\x13.execution.TestCaseR\x05tests\x12\"\n" +
	"\rtime_limit_ms\x18\x04 \x01(\x05R\vtimeLimitMs\x12&\n" +
	"\x0fmemory_limit_mb\x18\x05 \x01(\x05R\rmemoryLimitMb\"I\n" +
	"\bTestCase\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x12'\n" +
	"\x0fexpected_output\x18\x02 \x01(\tR\x0eexpectedOutput\"\xa4\x01\n" +
	"\n" +
	"TestResult\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\bR\x06passed\x12#\n" +
	"\ractual_output\x18\x03 \x01(\tR\factualOutput\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12*\n" +
	"\x11execution_time_ms\x18\x05 \x01(\x03R\x0fexecutionTimeMs\"\xa9\x01\n" +
	"\x13ExecuteTestResponse\x12\x1d\n" +
	"\n" +
	"all_passed\x18\x01 \x01(\bR\tallPassed\x12/\n" +
	"\aresults\x18\x02 \x03(\v2\x15.execution.TestResultR\aresults\x12!\n" +
	"\fpassed_count\x18\x03 \x01(\x05R\vpassedCount\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\">\n" +
	"\x19GetExecutionStatusRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"z\n" +
	"\x0fExecutionStatus\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\x86\x02\n" +
	"\x10ExecutionService\x12L\n" +
	"\vExecuteCode\x12\x1d.execution.ExecuteCodeRequest\x1a\x1e.execution.ExecuteCodeResponse\x12L\n" +
	"\vExecuteTest\x12\x1d.execution.ExecuteTestRequest\x1a\x1e.execution.ExecuteTestResponse\x12V\n" +
	"\x12GetExecutionStatus\x12$.execution.GetExecutionStatusRequest\x1a\x1a.execution.ExecutionStatusB\x1eZ\x1ccode-trainer/proto/executionb\x06proto3"

var (
	file_execution_execution_proto_rawDescOnce sync.Once
	file_execution_execution_proto_rawDescData []byte
)

func file_execution_execution_proto_rawDescGZIP() []byte {
	file_execution_execution_proto_rawDescOnce.Do(func() {
		file_execution_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_execution_execution_proto_rawDesc), len(file_execution_execution_proto_rawDesc)))
	})
	return file_execution_execution_proto_rawDescData
}

var file_execution_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_execution_execution_proto_goTypes = []any{
	(*ExecuteCodeRequest)(nil),        // 0: execution.ExecuteCodeRequest
	(*ExecuteCodeResponse)(nil),       // 1: execution.ExecuteCodeResponse
	(*ExecuteTestRequest)(nil),        // 2: execution.ExecuteTestRequest
	(*TestCase)(nil),                  // 3: execution.TestCase
	(*TestResult)(nil),                // 4: execution.TestResult
	(*ExecuteTestResponse)(nil),       // 5: execution.ExecuteTestResponse
	(*GetExecutionStatusRequest)(nil), // 6: execution.GetExecutionStatusRequest
	(*ExecutionStatus)(nil),           // 7: execution.ExecutionStatus
}
var file_execution_execution_proto_depIdxs = []int32{
	3, // 0: execution.ExecuteTestRequest.tests:type_name -> execution.TestCase
	4, // 1: execution.ExecuteTestResponse.results:type_name -> execution.TestResult
	0, // 2: execution.ExecutionService.ExecuteCode:input_type -> execution.ExecuteCodeRequest
	2, // 3: execution.ExecutionService.ExecuteTest:input_type -> execution.ExecuteTestRequest
	6, // 4: execution.ExecutionService.GetExecutionStatus:input_type -> execution.GetExecutionStatusRequest
	1, // 5: execution.ExecutionService.ExecuteCode:output_type -> execution.ExecuteCodeResponse
	5, // 6: execution.ExecutionService.ExecuteTest:output_type -> execution.ExecuteTestResponse
	7, // 7: execution.ExecutionService.GetExecutionStatus:output_type -> execution.ExecutionStatus
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_execution_execution_proto_init() }
func file_execution_execution_proto_init() {
	if File_execution_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_execution_execution_proto_rawDesc), len(file_execution_execution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_execution_execution_proto_goTypes,
		DependencyIndexes: file_execution_execution_proto_depIdxs,
		MessageInfos:      file_execution_execution_proto_msgTypes,
	}.Build()
	File_execution_execution_proto = out.File
	file_execution_execution_proto_goTypes = nil
	file_execution_execution_proto_depIdxs = nil
}
