// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: analytics/analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // task_started, task_completed, code_submitted
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEventRequest) Reset() {
	*x = TrackEventRequest{}
	mi := &file_analytics_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventRequest) ProtoMessage() {}

func (x *TrackEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventRequest.ProtoReflect.Descriptor instead.
func (*TrackEventRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *TrackEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TrackEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TrackEventRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TrackEventRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TrackEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEventResponse) Reset() {
	*x = TrackEventResponse{}
	mi := &file_analytics_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventResponse) ProtoMessage() {}

func (x *TrackEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventResponse.ProtoReflect.Descriptor instead.
func (*TrackEventResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *TrackEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrackEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type GetUserProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProgressRequest) Reset() {
	*x = GetUserProgressRequest{}
	mi := &file_analytics_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProgressRequest) ProtoMessage() {}

func (x *GetUserProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProgressRequest.ProtoReflect.Descriptor instead.
func (*GetUserProgressRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserProgress struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalTasksAttempted int32                  `protobuf:"varint,2,opt,name=total_tasks_attempted,json=totalTasksAttempted,proto3" json:"total_tasks_attempted,omitempty"`
	TotalTasksCompleted int32                  `protobuf:"varint,3,opt,name=total_tasks_completed,json=totalTasksCompleted,proto3" json:"total_tasks_completed,omitempty"`
	OverallScore        float32                `protobuf:"fixed32,4,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	TotalXp             int32                  `protobuf:"varint,5,opt,name=total_xp,json=totalXp,proto3" json:"total_xp,omitempty"`
	CurrentStreakDays   int32                  `protobuf:"varint,6,opt,name=current_streak_days,json=currentStreakDays,proto3" json:"current_streak_days,omitempty"`
	TasksByDifficulty   map[string]int32       `protobuf:"bytes,7,rep,name=tasks_by_difficulty,json=tasksByDifficulty,proto3" json:"tasks_by_difficulty,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	SkillsProgress      map[string]float32     `protobuf:"bytes,8,rep,name=skills_progress,json=skillsProgress,proto3" json:"skills_progress,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserProgress) Reset() {
	*x = UserProgress{}
	mi := &file_analytics_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProgress) ProtoMessage() {}

func (x *UserProgress) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProgress.ProtoReflect.Descriptor instead.
func (*UserProgress) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *UserProgress) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProgress) GetTotalTasksAttempted() int32 {
	if x != nil {
		return x.TotalTasksAttempted
	}
	return 0
}

func (x *UserProgress) GetTotalTasksCompleted() int32 {
	if x != nil {
		return x.TotalTasksCompleted
	}
	return 0
}

func (x *UserProgress) GetOverallScore() float32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *UserProgress) GetTotalXp() int32 {
	if x != nil {
		return x.TotalXp
	}
	return 0
}

func (x *UserProgress) GetCurrentStreakDays() int32 {
	if x != nil {
		return x.CurrentStreakDays
	}
	return 0
}

func (x *UserProgress) GetTasksByDifficulty() map[string]int32 {
	if x != nil {
		return x.TasksByDifficulty
	}
	return nil
}

func (x *UserProgress) GetSkillsProgress() map[string]float32 {
	if x != nil {
		return x.SkillsProgress
	}
	return nil
}

type GetLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timeframe     string                 `protobuf:"bytes,1,opt,name=timeframe,proto3" json:"timeframe,omitempty"` // weekly, monthly, all_time
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_analytics_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *GetLeaderboardRequest) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *GetLeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LeaderboardEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Rank           int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username       string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Score          int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	TasksCompleted int32                  `protobuf:"varint,5,opt,name=tasks_completed,json=tasksCompleted,proto3" json:"tasks_completed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_analytics_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaderboardEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LeaderboardEntry) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *LeaderboardEntry) GetTasksCompleted() int32 {
	if x != nil {
		return x.TasksCompleted
	}
	return 0
}

type Leaderboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Timeframe     string                 `protobuf:"bytes,2,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leaderboard) Reset() {
	*x = Leaderboard{}
	mi := &file_analytics_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leaderboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leaderboard) ProtoMessage() {}

func (x *Leaderboard) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leaderboard.ProtoReflect.Descriptor instead.
func (*Leaderboard) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *Leaderboard) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Leaderboard) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

type GetUserActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Days          int32                  `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserActivityRequest) Reset() {
	*x = GetUserActivityRequest{}
	mi := &file_analytics_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserActivityRequest) ProtoMessage() {}

func (x *GetUserActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserActivityRequest.ProtoReflect.Descriptor instead.
func (*GetUserActivityRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserActivityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserActivityRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type Activity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Date           string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	TasksCompleted int32                  `protobuf:"varint,2,opt,name=tasks_completed,json=tasksCompleted,proto3" json:"tasks_completed,omitempty"`
	XpEarned       int32                  `protobuf:"varint,3,opt,name=xp_earned,json=xpEarned,proto3" json:"xp_earned,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_analytics_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *Activity) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Activity) GetTasksCompleted() int32 {
	if x != nil {
		return x.TasksCompleted
	}
	return 0
}

func (x *Activity) GetXpEarned() int32 {
	if x != nil {
		return x.XpEarned
	}
	return 0
}

type UserActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Activities    []*Activity            `protobuf:"bytes,2,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserActivity) Reset() {
	*x = UserActivity{}
	mi := &file_analytics_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActivity) ProtoMessage() {}

func (x *UserActivity) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActivity.ProtoReflect.Descriptor instead.
func (*UserActivity) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *UserActivity) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserActivity) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

type GetTaskStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatsRequest) Reset() {
	*x = GetTaskStatsRequest{}
	mi := &file_analytics_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatsRequest) ProtoMessage() {}

func (x *GetTaskStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatsRequest.ProtoReflect.Descriptor instead.
func (*GetTaskStatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *GetTaskStatsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TotalAttempts      int32                  `protobuf:"varint,2,opt,name=total_attempts,json=totalAttempts,proto3" json:"total_attempts,omitempty"`
	SuccessfulAttempts int32                  `protobuf:"varint,3,opt,name=successful_attempts,json=successfulAttempts,proto3" json:"successful_attempts,omitempty"`
	SuccessRate        float32                `protobuf:"fixed32,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AverageScore       float32                `protobuf:"fixed32,5,opt,name=average_score,json=averageScore,proto3" json:"average_score,omitempty"`
	ScoreDistribution  map[string]int32       `protobuf:"bytes,6,rep,name=score_distribution,json=scoreDistribution,proto3" json:"score_distribution,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TaskStats) Reset() {
	*x = TaskStats{}
	mi := &file_analytics_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStats) ProtoMessage() {}

func (x *TaskStats) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStats.ProtoReflect.Descriptor instead.
func (*TaskStats) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *TaskStats) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStats) GetTotalAttempts() int32 {
	if x != nil {
		return x.TotalAttempts
	}
	return 0
}

func (x *TaskStats) GetSuccessfulAttempts() int32 {
	if x != nil {
		return x.SuccessfulAttempts
	}
	return 0
}

func (x *TaskStats) GetSuccessRate() float32 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *TaskStats) GetAverageScore() float32 {
	if x != nil {
		return x.AverageScore
	}
	return 0
}

func (x *TaskStats) GetScoreDistribution() map[string]int32 {
	if x != nil {
		return x.ScoreDistribution
	}
	return nil
}

var File_analytics_analytics_proto protoreflect.FileDescriptor

const file_analytics_analytics_proto_rawDesc = "" +
	"\n" +
	"\x19analytics/analytics.proto\x12\tanalytics\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x02\n" +
	"\x11TrackEventRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12F\n" +
	"\bmetadata\x18\x03 \x03(\v2*.analytics.TrackEventRequest.MetadataEntryR\bmetadata\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x12TrackEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\"1\n" +
	"\x16GetUserProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xbe\x04\n" +
	"\fUserProgress\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x122\n" +
	"\x15total_tasks_attempted\x18\x02 \x01(\x05R\x13totalTasksAttempted\x122\n" +
	"\x15total_tasks_completed\x18\x03 \x01(\x05R\x13totalTasksCompleted\x12#\n" +
	"\roverall_score\x18\x04 \x01(\x02R\foverallScore\x12\x19\n" +
	"\btotal_xp\x18\x05 \x01(\x05R\atotalXp\x12.\n" +
	"\x13current_streak_days\x18\x06 \x01(\x05R\x11currentStreakDays\x12^\n" +
	"\x13tasks_by_difficulty\x18\a \x03(\v2..analytics.UserProgress.TasksByDifficultyEntryR\x11tasksByDifficulty\x12T\n" +
	"\x0fskills_progress\x18\b \x03(\v2+.analytics.UserProgress.SkillsProgressEntryR\x0eskillsProgress\x1aD\n" +
	"\x16TasksByDifficultyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aA\n" +
	"\x13SkillsProgressEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"K\n" +
	"\x15GetLeaderboardRequest\x12\x1c\n" +
	"\ttimeframe\x18\x01 \x01(\tR\ttimeframe\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x9a\x01\n" +
	"\x10LeaderboardEntry\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12'\n" +
	"\x0ftasks_completed\x18\x05 \x01(\x05R\x0etasksCompleted\"b\n" +
	"\vLeaderboard\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.analytics.LeaderboardEntryR\aentries\x12\x1c\n" +
	"\ttimeframe\x18\x02 \x01(\tR\ttimeframe\"E\n" +
	"\x16GetUserActivityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04days\x18\x02 \x01(\x05R\x04days\"d\n" +
	"\bActivity\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12'\n" +
	"\x0ftasks_completed\x18\x02 \x01(\x05R\x0etasksCompleted\x12\x1b\n" +
	"\txp_earned\x18\x03 \x01(\x05R\bxpEarned\"\\\n" +
	"\fUserActivity\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x123\n" +
	"\n" +
	"activities\x18\x02 \x03(\v2\x13.analytics.ActivityR\n" +
	"activities\".\n" +
	"\x13GetTaskStatsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xe6\x02\n" +
	"\tTaskStats\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12%\n" +
	"\x0etotal_attempts\x18\x02 \x01(\x05R\rtotalAttempts\x12/\n" +
	"\x13successful_attempts\x18\x03 \x01(\x05R\x12successfulAttempts\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x02R\vsuccessRate\x12#\n" +
	"\raverage_score\x18\x05 \x01(\x02R\faverageScore\x12Z\n" +
	"\x12score_distribution\x18\x06 \x03(\v2+.analytics.TaskStats.ScoreDistributionEntryR\x11scoreDistribution\x1aD\n" +
	"\x16ScoreDistributionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012\x8d\x03\n" +
	"\x10AnalyticsService\x12I\n" +
	"\n" +
	"TrackEvent\x12\x1c.analytics.TrackEventRequest\x1a\x1d.analytics.TrackEventResponse\x12M\n" +
	"\x0fGetUserProgress\x12!.analytics.GetUserProgressRequest\x1a\x17.analytics.UserProgress\x12J\n" +
	"\x0eGetLeaderboard\x12 .analytics.GetLeaderboardRequest\x1a\x16.analytics.Leaderboard\x12M\n" +
	"\x0fGetUserActivity\x12!.analytics.GetUserActivityRequest\x1a\x17.analytics.UserActivity\x12D\n" +
	"\fGetTaskStats\x12\x1e.analytics.GetTaskStatsRequest\x1a\x14.analytics.TaskStatsB0Z.github.com/AllaxSydia/trenager/proto/analyticsb\x06proto3"

var (
	file_analytics_analytics_proto_rawDescOnce sync.Once
	file_analytics_analytics_proto_rawDescData []byte
)

func file_analytics_analytics_proto_rawDescGZIP() []byte {
	file_analytics_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_analytics_proto_rawDesc), len(file_analytics_analytics_proto_rawDesc)))
	})
	return file_analytics_analytics_proto_rawDescData
}

var file_analytics_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_analytics_analytics_proto_goTypes = []any{
	(*TrackEventRequest)(nil),      // 0: analytics.TrackEventRequest
	(*TrackEventResponse)(nil),     // 1: analytics.TrackEventResponse
	(*GetUserProgressRequest)(nil), // 2: analytics.GetUserProgressRequest
	(*UserProgress)(nil),           // 3: analytics.UserProgress
	(*GetLeaderboardRequest)(nil),  // 4: analytics.GetLeaderboardRequest
	(*LeaderboardEntry)(nil),       // 5: analytics.LeaderboardEntry
	(*Leaderboard)(nil),            // 6: analytics.Leaderboard
	(*GetUserActivityRequest)(nil), // 7: analytics.GetUserActivityRequest
	(*Activity)(nil),               // 8: analytics.Activity
	(*UserActivity)(nil),           // 9: analytics.UserActivity
	(*GetTaskStatsRequest)(nil),    // 10: analytics.GetTaskStatsRequest
	(*TaskStats)(nil),              // 11: analytics.TaskStats
	nil,                            // 12: analytics.TrackEventRequest.MetadataEntry
	nil,                            // 13: analytics.UserProgress.TasksByDifficultyEntry
	nil,                            // 14: analytics.UserProgress.SkillsProgressEntry
	nil,                            // 15: analytics.TaskStats.ScoreDistributionEntry
	(*timestamppb.Timestamp)(nil),  // 16: google.protobuf.Timestamp
}
var file_analytics_analytics_proto_depIdxs = []int32{
	12, // 0: analytics.TrackEventRequest.metadata:type_name -> analytics.TrackEventRequest.MetadataEntry
	16, // 1: analytics.TrackEventRequest.timestamp:type_name -> google.protobuf.Timestamp
	13, // 2: analytics.UserProgress.tasks_by_difficulty:type_name -> analytics.UserProgress.TasksByDifficultyEntry
	14, // 3: analytics.UserProgress.skills_progress:type_name -> analytics.UserProgress.SkillsProgressEntry
	5,  // 4: analytics.Leaderboard.entries:type_name -> analytics.LeaderboardEntry
	8,  // 5: analytics.UserActivity.activities:type_name -> analytics.Activity
	15, // 6: analytics.TaskStats.score_distribution:type_name -> analytics.TaskStats.ScoreDistributionEntry
	0,  // 7: analytics.AnalyticsService.TrackEvent:input_type -> analytics.TrackEventRequest
	2,  // 8: analytics.AnalyticsService.GetUserProgress:input_type -> analytics.GetUserProgressRequest
	4,  // 9: analytics.AnalyticsService.GetLeaderboard:input_type -> analytics.GetLeaderboardRequest
	7,  // 10: analytics.AnalyticsService.GetUserActivity:input_type -> analytics.GetUserActivityRequest
	10, // 11: analytics.AnalyticsService.GetTaskStats:input_type -> analytics.GetTaskStatsRequest
	1,  // 12: analytics.AnalyticsService.TrackEvent:output_type -> analytics.TrackEventResponse
	3,  // 13: analytics.AnalyticsService.GetUserProgress:output_type -> analytics.UserProgress
	6,  // 14: analytics.AnalyticsService.GetLeaderboard:output_type -> analytics.Leaderboard
	9,  // 15: analytics.AnalyticsService.GetUserActivity:output_type -> analytics.UserActivity
	11, // 16: analytics.AnalyticsService.GetTaskStats:output_type -> analytics.TaskStats
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_analytics_analytics_proto_init() }
func file_analytics_analytics_proto_init() {
	if File_analytics_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_analytics_proto_rawDesc), len(file_analytics_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_analytics_proto_msgTypes,
	}.Build()
	File_analytics_analytics_proto = out.File
	file_analytics_analytics_proto_goTypes = nil
	file_analytics_analytics_proto_depIdxs = nil
}
