// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: grading/grading.proto

package grading

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitSolutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSolutionRequest) Reset() {
	*x = SubmitSolutionRequest{}
	mi := &file_grading_grading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSolutionRequest) ProtoMessage() {}

func (x *SubmitSolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grading_grading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSolutionRequest.ProtoReflect.Descriptor instead.
func (*SubmitSolutionRequest) Descriptor() ([]byte, []int) {
	return file_grading_grading_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitSolutionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubmitSolutionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitSolutionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SubmitSolutionRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type SubmitSolutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SubmissionId  string                 `protobuf:"bytes,2,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Grade         *Grade                 `protobuf:"bytes,4,opt,name=grade,proto3" json:"grade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSolutionResponse) Reset() {
	*x = SubmitSolutionResponse{}
	mi := &file_grading_grading_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSolutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSolutionResponse) ProtoMessage() {}

func (x *SubmitSolutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grading_grading_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSolutionResponse.ProtoReflect.Descriptor instead.
func (*SubmitSolutionResponse) Descriptor() ([]byte, []int) {
	return file_grading_grading_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitSolutionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitSolutionResponse) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *SubmitSolutionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitSolutionResponse) GetGrade() *Grade {
	if x != nil {
		return x.Grade
	}
	return nil
}

type GetGradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradeRequest) Reset() {
	*x = GetGradeRequest{}
	mi := &file_grading_grading_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradeRequest) ProtoMessage() {}

func (x *GetGradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grading_grading_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradeRequest.ProtoReflect.Descriptor instead.
func (*GetGradeRequest) Descriptor() ([]byte, []int) {
	return file_grading_grading_proto_rawDescGZIP(), []int{2}
}

func (x *GetGradeRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

type Grade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	MaxScore      int32                  `protobuf:"varint,5,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // pending, passed, failed, partial
	Feedback      string                 `protobuf:"bytes,7,opt,name=feedback,proto3" json:"feedback,omitempty"`
	TestResults   []*TestResult          `protobuf:"bytes,8,rep,name=test_results,json=testResults,proto3" json:"test_results,omitempty"`
	SubmittedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	GradedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=graded_at,json=gradedAt,proto3" json:"graded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grade) Reset() {
	*x = Grade{}
	mi := &file_grading_grading_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grade) ProtoMessage() {}

func (x *Grade) ProtoReflect() protoreflect.Message {
	mi := &file_grading_grading_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grade.ProtoReflect.Descriptor instead.
func (*Grade) Descriptor() ([]byte, []int) {
	return file_grading_grading_proto_rawDescGZIP(), []int{3}
}

func (x *Grade) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *Grade) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Grade) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Grade) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Grade) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *Grade) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Grade) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *Grade) GetTestResults() []*TestResult {
	if x != nil {
		return x.TestResults
	}
	return nil
}

func (x *Grade) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *Grade) GetGradedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GradedAt
	}
	return nil
}

type TestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestName      string                 `protobuf:"bytes,1,opt,name=test_name,json=testName,proto3" json:"test_name,omitempty"`
	Passed        bool                   `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Expected      string                 `protobuf:"bytes,4,opt,name=expected,proto3" json:"expected,omitempty"`
	Score         int32                  `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	MaxScore      int32                  `protobuf:"varint,6,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResult) Reset() {
	*x = TestResult{}
	mi := &file_grading_grading_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResult) ProtoMessage() {}

func (x *TestResult) ProtoReflect() protoreflect.Message {
	mi := &file_grading_grading_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResult.ProtoReflect.Descriptor instead.
func (*TestResult) Descriptor() ([]byte, []int) {
	return file_grading_grading_proto_rawDescGZIP(), []int{4}
}

func (x *TestResult) GetTestName() string {
	if x != nil {
		return x.TestName
	}
	return ""
}

func (x *TestResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *TestResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TestResult) GetExpected() string {
	if x != nil {
		return x.Expected
	}
	return ""
}

func (x *TestResult) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *TestResult) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

type GetUserGradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserGradesRequest) Reset() {
	*x = GetUserGradesRequest{}
	mi := &file_grading_grading_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserGradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGradesRequest) ProtoMessage() {}

func (x *GetUserGradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grading_grading_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGradesRequest.ProtoReflect.Descriptor instead.
func (*GetUserGradesRequest) Descriptor() ([]byte, []int) {
	return file_grading_grading_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserGradesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserGradesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserGradesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetUserGradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grades        []*Grade               `protobuf:"bytes,1,rep,name=grades,proto3" json:"grades,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserGradesResponse) Reset() {
	*x = GetUserGradesResponse{}
	mi := &file_grading_grading_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserGradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGradesResponse) ProtoMessage() {}

func (x *GetUserGradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grading_grading_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGradesResponse.ProtoReflect.Descriptor instead.
func (*GetUserGradesResponse) Descriptor() ([]byte, []int) {
	return file_grading_grading_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserGradesResponse) GetGrades() []*Grade {
	if x != nil {
		return x.Grades
	}
	return nil
}

func (x *GetUserGradesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetTaskStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatisticsRequest) Reset() {
	*x = GetTaskStatisticsRequest{}
	mi := &file_grading_grading_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatisticsRequest) ProtoMessage() {}

func (x *GetTaskStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grading_grading_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetTaskStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_grading_grading_proto_rawDescGZIP(), []int{7}
}

func (x *GetTaskStatisticsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskStatistics struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TaskId                string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TotalSubmissions      int32                  `protobuf:"varint,2,opt,name=total_submissions,json=totalSubmissions,proto3" json:"total_submissions,omitempty"`
	SuccessfulSubmissions int32                  `protobuf:"varint,3,opt,name=successful_submissions,json=successfulSubmissions,proto3" json:"successful_submissions,omitempty"`
	AverageScore          float32                `protobuf:"fixed32,4,opt,name=average_score,json=averageScore,proto3" json:"average_score,omitempty"`
	ScoreDistribution     map[string]int32       `protobuf:"bytes,5,rep,name=score_distribution,json=scoreDistribution,proto3" json:"score_distribution,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TaskStatistics) Reset() {
	*x = TaskStatistics{}
	mi := &file_grading_grading_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatistics) ProtoMessage() {}

func (x *TaskStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_grading_grading_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatistics.ProtoReflect.Descriptor instead.
func (*TaskStatistics) Descriptor() ([]byte, []int) {
	return file_grading_grading_proto_rawDescGZIP(), []int{8}
}

func (x *TaskStatistics) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatistics) GetTotalSubmissions() int32 {
	if x != nil {
		return x.TotalSubmissions
	}
	return 0
}

func (x *TaskStatistics) GetSuccessfulSubmissions() int32 {
	if x != nil {
		return x.SuccessfulSubmissions
	}
	return 0
}

func (x *TaskStatistics) GetAverageScore() float32 {
	if x != nil {
		return x.AverageScore
	}
	return 0
}

func (x *TaskStatistics) GetScoreDistribution() map[string]int32 {
	if x != nil {
		return x.ScoreDistribution
	}
	return nil
}

var File_grading_grading_proto protoreflect.FileDescriptor

const file_grading_grading_proto_rawDesc = "" +
	"\n" +
	"\x15grading/grading.proto\x12\agrading\x1a\x1fgoogle/protobuf/timestamp.proto\"y\n" +
	"\x15SubmitSolutionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\"\x97\x01\n" +
	"\x16SubmitSolutionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rsubmission_id\x18\x02 \x01(\tR\fsubmissionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12$\n" +
	"\x05grade\x18\x04 \x01(\v2\x0e.grading.GradeR\x05grade\"6\n" +
	"\x0fGetGradeRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\"\xf5\x02\n" +
	"\x05Grade\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x1b\n" +
	"\tmax_score\x18\x05 \x01(\x05R\bmaxScore\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\bfeedback\x18\a \x01(\tR\bfeedback\x126\n" +
	"\ftest_results\x18\b \x03(\v2\x13.grading.TestResultR\vtestResults\x12=\n" +
	"\fsubmitted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\x127\n" +
	"\tgraded_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bgradedAt\"\xa8\x01\n" +
	"\n" +
	"TestResult\x12\x1b\n" +
	"\ttest_name\x18\x01 \x01(\tR\btestName\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\bR\x06passed\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x1a\n" +
	"\bexpected\x18\x04 \x01(\tR\bexpected\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\x12\x1b\n" +
	"\tmax_score\x18\x06 \x01(\x05R\bmaxScore\"`\n" +
	"\x14GetUserGradesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"U\n" +
	"\x15GetUserGradesResponse\x12&\n" +
	"\x06grades\x18\x01 \x03(\v2\x0e.grading.GradeR\x06grades\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"3\n" +
	"\x18GetTaskStatisticsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xd7\x02\n" +
	"\x0eTaskStatistics\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12+\n" +
	"\x11total_submissions\x18\x02 \x01(\x05R\x10totalSubmissions\x125\n" +
	"\x16successful_submissions\x18\x03 \x01(\x05R\x15successfulSubmissions\x12#\n" +
	"\raverage_score\x18\x04 \x01(\x02R\faverageScore\x12]\n" +
	"\x12score_distribution\x18\x05 \x03(\v2..grading.TaskStatistics.ScoreDistributionEntryR\x11scoreDistribution\x1aD\n" +
	"\x16ScoreDistributionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012\xba\x02\n" +
	"\x0eGradingService\x12Q\n" +
	"\x0eSubmitSolution\x12\x1e.grading.SubmitSolutionRequest\x1a\x1f.grading.SubmitSolutionResponse\x124\n" +
	"\bGetGrade\x12\x18.grading.GetGradeRequest\x1a\x0e.grading.Grade\x12N\n" +
	"\rGetUserGrades\x12\x1d.grading.GetUserGradesRequest\x1a\x1e.grading.GetUserGradesResponse\x12O\n" +
	"\x11GetTaskStatistics\x12!.grading.GetTaskStatisticsRequest\x1a\x17.grading.TaskStatisticsB\x1cZ\x1acode-trainer/proto/gradingb\x06proto3"

var (
	file_grading_grading_proto_rawDescOnce sync.Once
	file_grading_grading_proto_rawDescData []byte
)

func file_grading_grading_proto_rawDescGZIP() []byte {
	file_grading_grading_proto_rawDescOnce.Do(func() {
		file_grading_grading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grading_grading_proto_rawDesc), len(file_grading_grading_proto_rawDesc)))
	})
	return file_grading_grading_proto_rawDescData
}

var file_grading_grading_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_grading_grading_proto_goTypes = []any{
	(*SubmitSolutionRequest)(nil),    // 0: grading.SubmitSolutionRequest
	(*SubmitSolutionResponse)(nil),   // 1: grading.SubmitSolutionResponse
	(*GetGradeRequest)(nil),          // 2: grading.GetGradeRequest
	(*Grade)(nil),                    // 3: grading.Grade
	(*TestResult)(nil),               // 4: grading.TestResult
	(*GetUserGradesRequest)(nil),     // 5: grading.GetUserGradesRequest
	(*GetUserGradesResponse)(nil),    // 6: grading.GetUserGradesResponse
	(*GetTaskStatisticsRequest)(nil), // 7: grading.GetTaskStatisticsRequest
	(*TaskStatistics)(nil),           // 8: grading.TaskStatistics
	nil,                              // 9: grading.TaskStatistics.ScoreDistributionEntry
	(*timestamppb.Timestamp)(nil),    // 10: google.protobuf.Timestamp
}
var file_grading_grading_proto_depIdxs = []int32{
	3,  // 0: grading.SubmitSolutionResponse.grade:type_name -> grading.Grade
	4,  // 1: grading.Grade.test_results:type_name -> grading.TestResult
	10, // 2: grading.Grade.submitted_at:type_name -> google.protobuf.Timestamp
	10, // 3: grading.Grade.graded_at:type_name -> google.protobuf.Timestamp
	3,  // 4: grading.GetUserGradesResponse.grades:type_name -> grading.Grade
	9,  // 5: grading.TaskStatistics.score_distribution:type_name -> grading.TaskStatistics.ScoreDistributionEntry
	0,  // 6: grading.GradingService.SubmitSolution:input_type -> grading.SubmitSolutionRequest
	2,  // 7: grading.GradingService.GetGrade:input_type -> grading.GetGradeRequest
	5,  // 8: grading.GradingService.GetUserGrades:input_type -> grading.GetUserGradesRequest
	7,  // 9: grading.GradingService.GetTaskStatistics:input_type -> grading.GetTaskStatisticsRequest
	1,  // 10: grading.GradingService.SubmitSolution:output_type -> grading.SubmitSolutionResponse
	3,  // 11: grading.GradingService.GetGrade:output_type -> grading.Grade
	6,  // 12: grading.GradingService.GetUserGrades:output_type -> grading.GetUserGradesResponse
	8,  // 13: grading.GradingService.GetTaskStatistics:output_type -> grading.TaskStatistics
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_grading_grading_proto_init() }
func file_grading_grading_proto_init() {
	if File_grading_grading_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grading_grading_proto_rawDesc), len(file_grading_grading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grading_grading_proto_goTypes,
		DependencyIndexes: file_grading_grading_proto_depIdxs,
		MessageInfos:      file_grading_grading_proto_msgTypes,
	}.Build()
	File_grading_grading_proto = out.File
	file_grading_grading_proto_goTypes = nil
	file_grading_grading_proto_depIdxs = nil
}
