// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: grading/grading.proto

package grading

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GradingService_SubmitSolution_FullMethodName    = "/grading.GradingService/SubmitSolution"
	GradingService_GetGrade_FullMethodName          = "/grading.GradingService/GetGrade"
	GradingService_GetUserGrades_FullMethodName     = "/grading.GradingService/GetUserGrades"
	GradingService_GetTaskStatistics_FullMethodName = "/grading.GradingService/GetTaskStatistics"
)

// GradingServiceClient is the client API for GradingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GradingServiceClient interface {
	SubmitSolution(ctx context.Context, in *SubmitSolutionRequest, opts ...grpc.CallOption) (*SubmitSolutionResponse, error)
	GetGrade(ctx context.Context, in *GetGradeRequest, opts ...grpc.CallOption) (*Grade, error)
	GetUserGrades(ctx context.Context, in *GetUserGradesRequest, opts ...grpc.CallOption) (*GetUserGradesResponse, error)
	GetTaskStatistics(ctx context.Context, in *GetTaskStatisticsRequest, opts ...grpc.CallOption) (*TaskStatistics, error)
}

type gradingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGradingServiceClient(cc grpc.ClientConnInterface) GradingServiceClient {
	return &gradingServiceClient{cc}
}

func (c *gradingServiceClient) SubmitSolution(ctx context.Context, in *SubmitSolutionRequest, opts ...grpc.CallOption) (*SubmitSolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitSolutionResponse)
	err := c.cc.Invoke(ctx, GradingService_SubmitSolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradingServiceClient) GetGrade(ctx context.Context, in *GetGradeRequest, opts ...grpc.CallOption) (*Grade, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Grade)
	err := c.cc.Invoke(ctx, GradingService_GetGrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradingServiceClient) GetUserGrades(ctx context.Context, in *GetUserGradesRequest, opts ...grpc.CallOption) (*GetUserGradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserGradesResponse)
	err := c.cc.Invoke(ctx, GradingService_GetUserGrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradingServiceClient) GetTaskStatistics(ctx context.Context, in *GetTaskStatisticsRequest, opts ...grpc.CallOption) (*TaskStatistics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStatistics)
	err := c.cc.Invoke(ctx, GradingService_GetTaskStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GradingServiceServer is the server API for GradingService service.
// All implementations must embed UnimplementedGradingServiceServer
// for forward compatibility.
type GradingServiceServer interface {
	SubmitSolution(context.Context, *SubmitSolutionRequest) (*SubmitSolutionResponse, error)
	GetGrade(context.Context, *GetGradeRequest) (*Grade, error)
	GetUserGrades(context.Context, *GetUserGradesRequest) (*GetUserGradesResponse, error)
	GetTaskStatistics(context.Context, *GetTaskStatisticsRequest) (*TaskStatistics, error)
	mustEmbedUnimplementedGradingServiceServer()
}

// UnimplementedGradingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGradingServiceServer struct{}

func (UnimplementedGradingServiceServer) SubmitSolution(context.Context, *SubmitSolutionRequest) (*SubmitSolutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitSolution not implemented")
}
func (UnimplementedGradingServiceServer) GetGrade(context.Context, *GetGradeRequest) (*Grade, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGrade not implemented")
}
func (UnimplementedGradingServiceServer) GetUserGrades(context.Context, *GetUserGradesRequest) (*GetUserGradesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserGrades not implemented")
}
func (UnimplementedGradingServiceServer) GetTaskStatistics(context.Context, *GetTaskStatisticsRequest) (*TaskStatistics, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskStatistics not implemented")
}
func (UnimplementedGradingServiceServer) mustEmbedUnimplementedGradingServiceServer() {}
func (UnimplementedGradingServiceServer) testEmbeddedByValue()                        {}

// UnsafeGradingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GradingServiceServer will
// result in compilation errors.
type UnsafeGradingServiceServer interface {
	mustEmbedUnimplementedGradingServiceServer()
}

func RegisterGradingServiceServer(s grpc.ServiceRegistrar, srv GradingServiceServer) {
	// If the following call panics, it indicates UnimplementedGradingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GradingService_ServiceDesc, srv)
}

func _GradingService_SubmitSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitSolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradingServiceServer).SubmitSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradingService_SubmitSolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradingServiceServer).SubmitSolution(ctx, req.(*SubmitSolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradingService_GetGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradingServiceServer).GetGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradingService_GetGrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradingServiceServer).GetGrade(ctx, req.(*GetGradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradingService_GetUserGrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserGradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradingServiceServer).GetUserGrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradingService_GetUserGrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradingServiceServer).GetUserGrades(ctx, req.(*GetUserGradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradingService_GetTaskStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradingServiceServer).GetTaskStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradingService_GetTaskStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradingServiceServer).GetTaskStatistics(ctx, req.(*GetTaskStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GradingService_ServiceDesc is the grpc.ServiceDesc for GradingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GradingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grading.GradingService",
	HandlerType: (*GradingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitSolution",
			Handler:    _GradingService_SubmitSolution_Handler,
		},
		{
			MethodName: "GetGrade",
			Handler:    _GradingService_GetGrade_Handler,
		},
		{
			MethodName: "GetUserGrades",
			Handler:    _GradingService_GetUserGrades_Handler,
		},
		{
			MethodName: "GetTaskStatistics",
			Handler:    _GradingService_GetTaskStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grading/grading.proto",
}
